services:
  mongodb:
    image: mongo:5
    container_name: math-arena-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: math-arena
    volumes:
      - mongodb_data:/data/db
    networks:
      - math-arena-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: math-arena-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - math-arena-network

volumes:
  mongodb_data:
  rabbitmq_data:

networks:
  math-arena-network:
    driver: bridge